language: node_js
sudo: false
branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^(hot)?fix.*$/"
    - "/^v[0-9].*$/"
git:
  depth: 1
node_js:
  - 10
install: 
  - npm install
script:
  - npm test && npm run coverage
after_success:
  - IMAGE_TAG=$(echo $TRAVIS_COMMIT | cut -c 1-7)	
  - echo Building the Docker image...	
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;	
  - docker build -t $DOCKER_HUB_URL:latest .	
  - docker tag $DOCKER_HUB_URL:latest $DOCKER_HUB_URL:$IMAGE_TAG	
  - docker push $(DOCKER_HUB_URL)	
  # - echo Docker image pushed 	