language: node_js
sudo: false
branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^(hot)?fix.*$/"
    - "/^v[0-9].*$/"
git:
  depth: 1
node_js:
  - 10
install: 
  - npm install
script:
  - npm test && npm run coverage