apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-app
  labels:
    app: expressjs
  namespace: default
spec:
  selector:
    matchLabels:
      app: expressjs
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: expressjs
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - public
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - normal
      containers:
      - image: CONTAINER_IMAGE
        name: expressjs-app
        ports:
        - containerPort: 3000
          protocol: TCP